version: '3.8'
services:
  video-uploader:
    build: ./video-uploader
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  video-processor:
    build: ./video-processor
    ports:
      - "3002:3002"
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  video-fetcher:
    build: ./video-fetcher
    ports:
      - "3001:3001"
    environment:
      - AWS_REGION=${AWS_REGION}
  auth-service:
    build: ./auth-service
    ports:
      - "3003:3003"
    environment:
      - AWS_REGION=${AWS_REGION}
